/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import modelo.Curso;
import modelo.Estudiante;
import modelo.Nota;

/**
 *
 * @author Jonathan Pacheco R.
 * @version 0.1
 *
 */

public class AgregarNota extends javax.swing.JFrame {

    Curso cur = new Curso();
    Estudiante est = new Estudiante();
    Nota not = new Nota();
    DefaultTableModel model;
    
    public AgregarNota() {
        initComponents();
        cur.llenarComboCurso(cmb_curso);
        est.llenarJTEstudiante(tbl_nota, "");
        
        esconderColumna(6);
        esconderColumna(5);
        esconderColumna(4);
        esconderColumna(3);   
        model = (DefaultTableModel) tbl_nota.getModel();
        tbl_nota.setRowHeight(30);

        
    }
    
    private void esconderColumna(int colIndex) {
        TableColumn col = tbl_nota.getColumnModel().getColumn(colIndex);
        col.setMaxWidth(0);
        col.setMinWidth(0);
        col.setPreferredWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtf_id_estudiante = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_agregar_nota = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_nota = new javax.swing.JTable();
        txtf_nota = new javax.swing.JTextField();
        cmb_curso = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtf_comentario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        jLabel1.setText("Agregar notas");

        jLabel2.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        jLabel2.setText("Nro. identificador de estudiante:");

        txtf_id_estudiante.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtf_id_estudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_id_estudianteActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        jLabel8.setText("Nota:");

        btn_agregar_nota.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btn_agregar_nota.setText("AGREGAR");
        btn_agregar_nota.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 102)));
        btn_agregar_nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_notaActionPerformed(evt);
            }
        });

        btn_cancelar.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btn_cancelar.setText("CANCELAR");
        btn_cancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        jLabel3.setText("Nro. identificador del curso:");

        tbl_nota.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tbl_nota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Nombre(s)", "Apellido(s)", "Sexo", "Fecha nac.", "Teléfono", "Dirección"
            }
        ));
        tbl_nota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_notaMouseClicked(evt);
            }
        });
        tbl_nota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_notaKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_nota);

        txtf_nota.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtf_nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_notaActionPerformed(evt);
            }
        });

        cmb_curso.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        jLabel9.setText("Comentario:");

        txtf_comentario.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtf_comentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_comentarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btn_agregar_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addComponent(txtf_id_estudiante)
                    .addComponent(txtf_nota)
                    .addComponent(cmb_curso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addComponent(txtf_comentario))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtf_id_estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_curso, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtf_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtf_comentario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_agregar_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtf_id_estudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_id_estudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_id_estudianteActionPerformed

    private void btn_agregar_notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_notaActionPerformed

        int idEst = Integer.valueOf(txtf_id_estudiante.getText());
        int idCur = cur.getIdCurso(cmb_curso.getSelectedItem().toString());
        double nota = Double.valueOf(txtf_nota.getText());
        System.out.println(idCur);
        not.inUpDelNota('i', idEst, idCur, nota, txtf_comentario.getText());
        
//        AgregarCurso aCur = new AgregarCurso();
//        aCur.setVisible(true);
//        aCur.pack();
//        aCur.setLocationRelativeTo(null);
//        aCur.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btn_agregar_notaActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
//        if (!txtf_id_curso.getText().equals("")) {
//            int id = Integer.valueOf(txtf_id_curso.getText());
//            cur.inUpDelCurso('b', id, null, null);
//            GestionarCurso.tbl_cursos.setModel(new DefaultTableModel(null, new Object[]{"Identificador","Nombre","Créditos"}));
//            cur.llenarJTCurso(GestionarCurso.tbl_cursos);
//            txtf_id_curso.setText("");
//            txtf_id_curso.setText("");
//            spn_creditos.setValue(0);
//        }
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void tbl_notaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_notaMouseClicked

        int rowIndex = tbl_nota.getSelectedRow();
        txtf_id_estudiante.setText(tbl_nota.getValueAt(rowIndex, 0).toString());

//        int rowIndex = tbl_nota.getSelectedRow();
//
//        if (model.getValueAt(rowIndex, 3).toString().equals("Masculino")) {
//            rbtn_mas.setSelected(true);
//            rbtn_fem.setSelected(false);
//        } else {
//            rbtn_fem.setSelected(true);
//            rbtn_mas.setSelected(false);
//        }
//
//        Date nac;
//        try {
//            nac = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
//            dch_nacimiento.setDate(nac);
//
//        } catch (ParseException ex) {
//            Logger.getLogger(GestionarEstudiante.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//        txtf_id_est.setText(model.getValueAt(rowIndex, 0).toString());
//        txtf_nombre.setText(model.getValueAt(rowIndex, 1).toString());
//        txtf_apellido.setText(model.getValueAt(rowIndex, 2).toString());
//        txtf_telefono.setText(model.getValueAt(rowIndex, 5).toString());
//        txta_direccion.setText(model.getValueAt(rowIndex, 6).toString());

    }//GEN-LAST:event_tbl_notaMouseClicked

    private void tbl_notaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_notaKeyReleased

//        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
//            int rowIndex = tbl_nota.getSelectedRow();
//            txtf_id_est.setText(model.getValueAt(rowIndex, 0).toString());
//            txtf_nombre.setText(model.getValueAt(rowIndex, 1).toString());
//            txtf_apellido.setText(model.getValueAt(rowIndex, 2).toString());
//            txtf_telefono.setText(model.getValueAt(rowIndex, 5).toString());
//            txta_direccion.setText(model.getValueAt(rowIndex, 6).toString());
//
//            if (model.getValueAt(rowIndex, 3).toString().equals("Masculino")) {
//                rbtn_mas.setSelected(true);
//                rbtn_fem.setSelected(false);
//            } else {
//                rbtn_fem.setSelected(true);
//                rbtn_mas.setSelected(false);
//            }
//
//            Date nac;
//            try {
//                nac = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
//                dch_nacimiento.setDate(nac);
//
//            } catch (ParseException ex) {
//                Logger.getLogger(GestionarEstudiante.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }

    }//GEN-LAST:event_tbl_notaKeyReleased

    private void txtf_notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_notaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_notaActionPerformed

    private void txtf_comentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_comentarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_comentarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarNota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar_nota;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JComboBox<String> cmb_curso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable tbl_nota;
    private javax.swing.JTextField txtf_comentario;
    private javax.swing.JTextField txtf_id_estudiante;
    private javax.swing.JTextField txtf_nota;
    // End of variables declaration//GEN-END:variables
}
