package vista;

import javax.swing.JFrame;

/**
 *
 * @author Jonathan Pacheco R.
 * @version 0.1
 * 
 */
public class FormularioPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormularioPrincipal
     */
    public FormularioPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_bienvenido = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_cant_est = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_cant_cur = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        meni_agregar_est = new javax.swing.JMenuItem();
        meni_gestionar_est = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        meni_agregar_curso = new javax.swing.JMenuItem();
        meni_gestionar_curso = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        meni_agregar_nota = new javax.swing.JMenuItem();
        meni_gestionar_nota = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_bienvenido.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        lbl_bienvenido.setText("Hola, <#####>");

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_cant_est.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        lbl_cant_est.setText("Cantidad de estudiantes: <###>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_cant_est)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_cant_est)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(247, 247, 247));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_cant_cur.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        lbl_cant_cur.setText("Cantidad de cursos: <###>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_cant_cur)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_cant_cur)
                .addContainerGap())
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(105, 40));

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reading-book.png"))); // NOI18N
        jMenu3.setText("Estudiantes      ");

        meni_agregar_est.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add-user.png"))); // NOI18N
        meni_agregar_est.setText("Agregar");
        meni_agregar_est.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meni_agregar_estActionPerformed(evt);
            }
        });
        jMenu3.add(meni_agregar_est);

        meni_gestionar_est.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/users.png"))); // NOI18N
        meni_gestionar_est.setText("Gestionar");
        meni_gestionar_est.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meni_gestionar_estActionPerformed(evt);
            }
        });
        jMenu3.add(meni_gestionar_est);

        jMenuBar1.add(jMenu3);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/online-course.png"))); // NOI18N
        jMenu1.setText("Cursos    ");

        meni_agregar_curso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plus.png"))); // NOI18N
        meni_agregar_curso.setText("Agregar");
        meni_agregar_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meni_agregar_cursoActionPerformed(evt);
            }
        });
        jMenu1.add(meni_agregar_curso);

        meni_gestionar_curso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit.png"))); // NOI18N
        meni_gestionar_curso.setText("Gestionar");
        meni_gestionar_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meni_gestionar_cursoActionPerformed(evt);
            }
        });
        jMenu1.add(meni_gestionar_curso);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1940762.png"))); // NOI18N
        jMenu2.setText("Notas");

        meni_agregar_nota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plus.png"))); // NOI18N
        meni_agregar_nota.setText("Agregar");
        meni_agregar_nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meni_agregar_notaActionPerformed(evt);
            }
        });
        jMenu2.add(meni_agregar_nota);

        meni_gestionar_nota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit.png"))); // NOI18N
        meni_gestionar_nota.setText("Gestionar");
        meni_gestionar_nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meni_gestionar_notaActionPerformed(evt);
            }
        });
        jMenu2.add(meni_gestionar_nota);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_bienvenido)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lbl_bienvenido)
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meni_agregar_estActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meni_agregar_estActionPerformed
        AgregarEstudiante aEst = new AgregarEstudiante();
        aEst.setVisible(true);
        aEst.pack();
        aEst.setLocationRelativeTo(null);
        aEst.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_meni_agregar_estActionPerformed

    private void meni_gestionar_estActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meni_gestionar_estActionPerformed
        GestionarEstudiante gEst = new GestionarEstudiante();
        gEst.setVisible(true);
        gEst.pack();
        gEst.setLocationRelativeTo(null);
        gEst.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_meni_gestionar_estActionPerformed

    private void meni_agregar_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meni_agregar_cursoActionPerformed
        AgregarCurso aCur = new AgregarCurso();
        aCur.setVisible(true);
        aCur.pack();
        aCur.setLocationRelativeTo(null);
        aCur.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_meni_agregar_cursoActionPerformed

    private void meni_gestionar_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meni_gestionar_cursoActionPerformed
        GestionarCurso gCur = new GestionarCurso();
        gCur.setVisible(true);
        gCur.pack();
        gCur.setLocationRelativeTo(null);
        gCur.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_meni_gestionar_cursoActionPerformed

    private void meni_agregar_notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meni_agregar_notaActionPerformed
        AgregarNota aNot = new AgregarNota();
        aNot.setVisible(true);
        aNot.pack();
        aNot.setLocationRelativeTo(null);
        aNot.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_meni_agregar_notaActionPerformed

    private void meni_gestionar_notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meni_gestionar_notaActionPerformed
        GestionarNota gNot = new GestionarNota();
        gNot.setVisible(true);
        gNot.pack();
        gNot.setLocationRelativeTo(null);
        gNot.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_meni_gestionar_notaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel lbl_bienvenido;
    public static javax.swing.JLabel lbl_cant_cur;
    public static javax.swing.JLabel lbl_cant_est;
    private javax.swing.JMenuItem meni_agregar_curso;
    private javax.swing.JMenuItem meni_agregar_est;
    private javax.swing.JMenuItem meni_agregar_nota;
    private javax.swing.JMenuItem meni_gestionar_curso;
    private javax.swing.JMenuItem meni_gestionar_est;
    private javax.swing.JMenuItem meni_gestionar_nota;
    // End of variables declaration//GEN-END:variables
}
