package vista;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import modelo.Nota;

/**
 *
 * @author Jonathan Pacheco R.
 * @version 0.1
 *
 */

public class GestionarNota extends javax.swing.JFrame {

    /**
     * Creates new form GestionarNota
     */
    Nota nt = new Nota();
    
    public GestionarNota() {
        initComponents();
        nt.llenarJTNota(tbl_g_nota);
        tbl_g_nota.setRowHeight(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtf_id_estudiante_g = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btn_agregar_nota2 = new javax.swing.JButton();
        btn_eliminar2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_g_nota = new javax.swing.JTable();
        txtf_nota_g = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtf_comentario_g = new javax.swing.JTextField();
        txtf_id_curso_g = new javax.swing.JTextField();
        btn_editar_nota2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        jLabel7.setText("Gestión de notas");

        jLabel12.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        jLabel12.setText("Nro. identificador de estudiante:");

        txtf_id_estudiante_g.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtf_id_estudiante_g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_id_estudiante_gActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        jLabel13.setText("Nota:");

        btn_agregar_nota2.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btn_agregar_nota2.setText("AGREGAR");
        btn_agregar_nota2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 102)));
        btn_agregar_nota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_nota2ActionPerformed(evt);
            }
        });

        btn_eliminar2.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btn_eliminar2.setText("ELIMINAR");
        btn_eliminar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        btn_eliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        jLabel14.setText("Nro. identificador del curso:");

        tbl_g_nota.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tbl_g_nota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id. estudiante", "Id. curso", "Nota", "Comentario"
            }
        ));
        tbl_g_nota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_g_notaMouseClicked(evt);
            }
        });
        tbl_g_nota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_g_notaKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_g_nota);

        txtf_nota_g.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtf_nota_g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_nota_gActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        jLabel15.setText("Comentario:");

        txtf_comentario_g.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtf_comentario_g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_comentario_gActionPerformed(evt);
            }
        });

        txtf_id_curso_g.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtf_id_curso_g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_id_curso_gActionPerformed(evt);
            }
        });

        btn_editar_nota2.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btn_editar_nota2.setText("EDITAR");
        btn_editar_nota2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        btn_editar_nota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editar_nota2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtf_id_estudiante_g, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                        .addComponent(txtf_nota_g)
                        .addComponent(txtf_comentario_g)
                        .addComponent(txtf_id_curso_g))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_agregar_nota2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_editar_nota2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_eliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtf_id_estudiante_g, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtf_id_curso_g, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtf_nota_g, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(txtf_comentario_g, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_agregar_nota2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_editar_nota2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_eliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtf_id_estudiante_gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_id_estudiante_gActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_id_estudiante_gActionPerformed

    private void btn_agregar_nota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_nota2ActionPerformed
        AgregarNota aNot = new AgregarNota();
        aNot.setVisible(true);
        aNot.pack();
        aNot.setLocationRelativeTo(null);
        aNot.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btn_agregar_nota2ActionPerformed

    private void btn_eliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar2ActionPerformed
        int idEs = Integer.valueOf(txtf_id_estudiante_g.getText()),
                idCu = Integer.valueOf(txtf_id_curso_g.getText());
        
        nt.inUpDelNota('b', idEs, idCu, null, null);
        tbl_g_nota.setModel(new DefaultTableModel(null, new Object[]{"Id. estudiante", "Id. curso", "Nota", "Comentario"}));
        nt.llenarJTNota(tbl_g_nota);
    }//GEN-LAST:event_btn_eliminar2ActionPerformed

    private void tbl_g_notaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_g_notaMouseClicked

        int rowIndex = tbl_g_nota.getSelectedRow();
        txtf_id_estudiante_g.setText(tbl_g_nota.getValueAt(rowIndex, 0).toString());
        txtf_id_curso_g.setText(tbl_g_nota.getValueAt(rowIndex, 1).toString());
        txtf_nota_g.setText(tbl_g_nota.getValueAt(rowIndex, 2).toString());
        txtf_comentario_g.setText(tbl_g_nota.getValueAt(rowIndex, 3).toString());

    }//GEN-LAST:event_tbl_g_notaMouseClicked

    private void tbl_g_notaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_g_notaKeyReleased

        //        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            //            int rowIndex = tbl_nota.getSelectedRow();
            //            txtf_id_est.setText(model.getValueAt(rowIndex, 0).toString());
            //            txtf_nombre.setText(model.getValueAt(rowIndex, 1).toString());
            //            txtf_apellido.setText(model.getValueAt(rowIndex, 2).toString());
            //            txtf_telefono.setText(model.getValueAt(rowIndex, 5).toString());
            //            txta_direccion.setText(model.getValueAt(rowIndex, 6).toString());
            //
            //            if (model.getValueAt(rowIndex, 3).toString().equals("Masculino")) {
                //                rbtn_mas.setSelected(true);
                //                rbtn_fem.setSelected(false);
                //            } else {
                //                rbtn_fem.setSelected(true);
                //                rbtn_mas.setSelected(false);
                //            }
            //
            //            Date nac;
            //            try {
                //                nac = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
                //                dch_nacimiento.setDate(nac);
                //
                //            } catch (ParseException ex) {
                //                Logger.getLogger(GestionarEstudiante.class.getName()).log(Level.SEVERE, null, ex);
                //            }
            //        }
    }//GEN-LAST:event_tbl_g_notaKeyReleased

    private void txtf_nota_gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_nota_gActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_nota_gActionPerformed

    private void txtf_comentario_gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_comentario_gActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_comentario_gActionPerformed

    private void txtf_id_curso_gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_id_curso_gActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_id_curso_gActionPerformed

    private void btn_editar_nota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editar_nota2ActionPerformed
        int idEs = Integer.valueOf(txtf_id_estudiante_g.getText()),
                idCu = Integer.valueOf(txtf_id_curso_g.getText());
        double not = Double.valueOf(txtf_nota_g.getText());
        String com = txtf_comentario_g.getText();
        nt.inUpDelNota('e', idEs, idCu, not, com);
        tbl_g_nota.setModel(new DefaultTableModel(null, new Object[]{"Id. estudiante", "Id. curso", "Nota", "Comentario"}));
        nt.llenarJTNota(GestionarNota.tbl_g_nota);
    }//GEN-LAST:event_btn_editar_nota2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarNota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar_nota2;
    private javax.swing.JButton btn_editar_nota2;
    private javax.swing.JButton btn_eliminar2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTable tbl_g_nota;
    private javax.swing.JTextField txtf_comentario_g;
    private javax.swing.JTextField txtf_id_curso_g;
    private javax.swing.JTextField txtf_id_estudiante_g;
    private javax.swing.JTextField txtf_nota_g;
    // End of variables declaration//GEN-END:variables
}
