package vista;

import com.sun.glass.events.KeyEvent;
import controlador.MiFuncion;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Estudiante;

/**
 *
 * @author Jonathan Pacheco R.
 * @version 0.1
 * 
 */
public class GestionarEstudiante extends javax.swing.JFrame {

    Estudiante est = new Estudiante();
    DefaultTableModel model; 
    int rowIndex;
    
    public GestionarEstudiante() {
        initComponents();
        est.llenarJTEstudiante(tbl_estudiantes, "");
        ButtonGroup bg = new ButtonGroup();
        bg.add(rbtn_fem);
        bg.add(rbtn_mas);
        model = (DefaultTableModel) tbl_estudiantes.getModel();
        tbl_estudiantes.setRowHeight(30);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtf_id_est = new javax.swing.JTextField();
        txtf_apellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtf_telefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rbtn_fem = new javax.swing.JRadioButton();
        rbtn_mas = new javax.swing.JRadioButton();
        dch_nacimiento = new com.toedter.calendar.JDateChooser();
        btn_agregar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtf_nombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_direccion = new javax.swing.JTextArea();
        btn_editar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_estudiantes = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtf_buscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        jLabel1.setText("Gestión de estudiantes");

        jLabel2.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        jLabel2.setText("Nro. identificador:");

        txtf_id_est.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtf_id_est.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_id_estActionPerformed(evt);
            }
        });

        txtf_apellido.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        jLabel3.setText("Apellido(s):");

        jLabel4.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        jLabel4.setText("Sexo:");

        jLabel5.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        jLabel5.setText("Fecha de nacimiento:");

        txtf_telefono.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtf_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_telefonoActionPerformed(evt);
            }
        });
        txtf_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtf_telefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_telefonoKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        jLabel6.setText("Teléfono:");

        jLabel7.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        jLabel7.setText("Dirección:");

        rbtn_fem.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        rbtn_fem.setText("Femenino");

        rbtn_mas.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        rbtn_mas.setText("Masculino");

        dch_nacimiento.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N

        btn_agregar.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btn_agregar.setText("AGREGAR");
        btn_agregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 102)));
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_eliminar.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        jLabel8.setText("Nombre(s):");

        txtf_nombre.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N

        txta_direccion.setColumns(20);
        txta_direccion.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txta_direccion.setRows(5);
        jScrollPane1.setViewportView(txta_direccion);

        btn_editar.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btn_editar.setText("EDITAR");
        btn_editar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtn_fem)
                        .addGap(18, 18, 18)
                        .addComponent(rbtn_mas))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtf_telefono)
                    .addComponent(dch_nacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtf_apellido)
                    .addComponent(txtf_nombre)
                    .addComponent(txtf_id_est))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtf_id_est, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_fem)
                    .addComponent(rbtn_mas))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dch_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tbl_estudiantes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tbl_estudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Nombre(s)", "Apellido(s)", "Sexo", "Fecha nac.", "Teléfono", "Dirección"
            }
        ));
        tbl_estudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_estudiantesMouseClicked(evt);
            }
        });
        tbl_estudiantes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_estudiantesKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_estudiantes);

        jLabel9.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel9.setText("Ingresa el término a buscar:");

        txtf_buscar.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtf_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_buscarActionPerformed(evt);
            }
        });
        txtf_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtf_buscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtf_buscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_buscarKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtf_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_telefonoActionPerformed

    private void txtf_telefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_telefonoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_telefonoKeyPressed

    private void txtf_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_telefonoKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtf_telefonoKeyTyped

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        /*
        ALTER TABLE nota
        add CONSTRAINT fk_nota_estudiante
        FOREIGN KEY(`id_estudiante`)
        REFERENCES estudiante (id)
        ON DELETE CASCADE
        */                
                
        if (txtf_id_est.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Selecciona a un estudiante primero");
        } else {
            int id = Integer.valueOf(txtf_id_est.getText());
            est.inUpDelEstudiante('b', id, null, null, null, null, null, null);
            est.llenarJTEstudiante(tbl_estudiantes, "");
            tbl_estudiantes.setModel(new DefaultTableModel(null, new Object[]{"Identificador", "Nombre(s)", "Apellido(s)", "Sexo", "Fecha nac.", "Teléfono", "Dirección"}));
            est.llenarJTEstudiante(tbl_estudiantes, txtf_buscar.getText());
            FormularioPrincipal.lbl_cant_est.setText("Cantidad de estudiantes: "+Integer.toString(MiFuncion.contarData("estudiante")));

            txtf_id_est.setText("");
            txtf_nombre.setText("");
            txtf_apellido.setText("");
            txtf_telefono.setText("");
            txta_direccion.setText("");
            rbtn_fem.setSelected(false);
            rbtn_mas.setSelected(false);
            dch_nacimiento.setDate(null);

        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void txtf_id_estActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_id_estActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_id_estActionPerformed

    public boolean verifText() {
        // Valida que no haya campos vacíos
        if (txtf_nombre.getText().equals("") || txtf_apellido.getText().equals("")
                || txtf_telefono.getText().equals("") || txta_direccion.getText().equals("")
                || txtf_id_est.getText().equals("") || dch_nacimiento.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
            return false;
            // Evita que se elija una fecha futura
        } else if (dch_nacimiento.getDate().compareTo(new Date()) > 0) {
            JOptionPane.showMessageDialog(null, "Fecha no válida");
            return false;
        } else {
            return true;
        }
    }
    
    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        String nombre = txtf_nombre.getText();
        String apellido = txtf_apellido.getText();
        String telefono = txtf_telefono.getText();
        String direccion = txta_direccion.getText();
        int id = Integer.valueOf(txtf_id_est.getText());
        String sexo = "";
        if (rbtn_fem.isSelected()) {
            sexo = "Femenino";
        } else if (rbtn_mas.isSelected()) {
            sexo = "Masculino";
        }

        // Registro verificado de nuevos estudiantes
        if (verifText()) {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String nacimiento = dateFormat.format(dch_nacimiento.getDate());
            Estudiante est = new Estudiante();
            est.inUpDelEstudiante('e', id, nombre, apellido, sexo, nacimiento, telefono, direccion);
            //FormularioPrincipal.lbl_cant_est.setText("Cantidad de estudiantes: "+Integer.toString(MiFuncion.contarData("estudiante")));
        }
        tbl_estudiantes.setModel(new DefaultTableModel(null, new Object[]{"Identificador", "Nombre(s)", "Apellido(s)", "Sexo", "Fecha nac.", "Teléfono", "Dirección"}));
        est.llenarJTEstudiante(tbl_estudiantes, "");
    }//GEN-LAST:event_btn_editarActionPerformed

    private void tbl_estudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_estudiantesMouseClicked
        int rowIndex = tbl_estudiantes.getSelectedRow();
        
        if (model.getValueAt(rowIndex, 3).toString().equals("Masculino")) {
            rbtn_mas.setSelected(true);
            rbtn_fem.setSelected(false);
        } else {
            rbtn_fem.setSelected(true);
            rbtn_mas.setSelected(false);
        }
        
        Date nac;
        try {
            nac = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
            dch_nacimiento.setDate(nac);
                    
        } catch (ParseException ex) {
            Logger.getLogger(GestionarEstudiante.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtf_id_est.setText(model.getValueAt(rowIndex, 0).toString());
        txtf_nombre.setText(model.getValueAt(rowIndex, 1).toString());
        txtf_apellido.setText(model.getValueAt(rowIndex, 2).toString());
        txtf_telefono.setText(model.getValueAt(rowIndex, 5).toString());
        txta_direccion.setText(model.getValueAt(rowIndex, 6).toString());
        
    }//GEN-LAST:event_tbl_estudiantesMouseClicked

    private void txtf_buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_buscarKeyTyped
        
    }//GEN-LAST:event_txtf_buscarKeyTyped

    private void txtf_buscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_buscarKeyPressed

    }//GEN-LAST:event_txtf_buscarKeyPressed

    private void txtf_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_buscarKeyReleased
        tbl_estudiantes.setModel(new DefaultTableModel(null, new Object[]{"Identificador", "Nombre(s)", "Apellido(s)", "Sexo", "Fecha nac.", "Teléfono", "Dirección"}));
        est.llenarJTEstudiante(tbl_estudiantes, txtf_buscar.getText());
    }//GEN-LAST:event_txtf_buscarKeyReleased

    private void tbl_estudiantesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_estudiantesKeyReleased
        
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            int rowIndex = tbl_estudiantes.getSelectedRow();            
            txtf_id_est.setText(model.getValueAt(rowIndex, 0).toString());
            txtf_nombre.setText(model.getValueAt(rowIndex, 1).toString());
            txtf_apellido.setText(model.getValueAt(rowIndex, 2).toString());
            txtf_telefono.setText(model.getValueAt(rowIndex, 5).toString());
            txta_direccion.setText(model.getValueAt(rowIndex, 6).toString());
            
            if (model.getValueAt(rowIndex, 3).toString().equals("Masculino")) {
                rbtn_mas.setSelected(true);
                rbtn_fem.setSelected(false);
            } else {
                rbtn_fem.setSelected(true);
                rbtn_mas.setSelected(false);
            }
            
            Date nac;
            try {
                nac = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
                dch_nacimiento.setDate(nac);

            } catch (ParseException ex) {
                Logger.getLogger(GestionarEstudiante.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_tbl_estudiantesKeyReleased

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        AgregarEstudiante aEst = new AgregarEstudiante();
        aEst.setVisible(true);
        aEst.pack();
        aEst.setLocationRelativeTo(null);
        aEst.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        //        String nombre = txtf_id_est.getText();
        //        String apellido = txtf_apellido.getText();
        //        String telefono = txtf_telefono.getText();
        //        String direccion = txta_direccion.getText();
        //        String sexo = "Masculino";
        //        if (rbtn_fem.isSelected()) {
            //            sexo = "Femenino";
            //        }
        //
        //        // Registro verificado de nuevos estudiantes
        //        if (verifText()) {
            //            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            //            String nacimiento = dateFormat.format(dch_nacimiento.getDate());
            //            Estudiante est = new Estudiante();
            //            est.inUpDelEstudiante('i', null, nombre, apellido, sexo, nacimiento, telefono, direccion);
            //            FormularioPrincipal.lbl_cant_est.setText("Cantidad de estudiantes: "+Integer.toString(MiFuncion.contarData("estudiante")));
            //        }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void txtf_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private com.toedter.calendar.JDateChooser dch_nacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbtn_fem;
    private javax.swing.JRadioButton rbtn_mas;
    public static javax.swing.JTable tbl_estudiantes;
    private javax.swing.JTextArea txta_direccion;
    private javax.swing.JTextField txtf_apellido;
    private javax.swing.JTextField txtf_buscar;
    private javax.swing.JTextField txtf_id_est;
    private javax.swing.JTextField txtf_nombre;
    private javax.swing.JTextField txtf_telefono;
    // End of variables declaration//GEN-END:variables
}
