package vista;

import bd.MiConexion;
import controlador.MiFuncion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jonathan Pacheco R.
 * @version 0.1
 * 
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        lbl_usuario_asterisco.setVisible(false);
        lbl_contrasenna_asterisco.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_ingreso = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        lbl_contrasenna = new javax.swing.JLabel();
        txtf_usuario = new javax.swing.JTextField();
        txtp_contrasenna = new javax.swing.JPasswordField();
        btn_entrar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        lbl_usuario_asterisco = new javax.swing.JLabel();
        lbl_contrasenna_asterisco = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        lbl_ingreso.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        lbl_ingreso.setText("Gestión de estudiantes");

        lbl_usuario.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        lbl_usuario.setText("Nombre de usuario:");

        lbl_contrasenna.setFont(new java.awt.Font("Myriad Pro", 0, 13)); // NOI18N
        lbl_contrasenna.setText("Contraseña:");

        txtf_usuario.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N

        txtp_contrasenna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtp_contrasennaActionPerformed(evt);
            }
        });

        btn_entrar.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btn_entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/enter.png"))); // NOI18N
        btn_entrar.setText("ENTRAR");
        btn_entrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        btn_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entrarActionPerformed(evt);
            }
        });

        btn_cancelar.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N
        btn_cancelar.setText("CANCELAR");
        btn_cancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 51, 0)));
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        lbl_usuario_asterisco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_usuario_asterisco.setForeground(new java.awt.Color(255, 51, 0));
        lbl_usuario_asterisco.setText("*");

        lbl_contrasenna_asterisco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_contrasenna_asterisco.setForeground(new java.awt.Color(255, 51, 0));
        lbl_contrasenna_asterisco.setText("*");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/university.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(lbl_ingreso)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_contrasenna)
                            .addComponent(lbl_usuario)
                            .addComponent(txtf_usuario)
                            .addComponent(txtp_contrasenna, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_usuario_asterisco)
                            .addComponent(lbl_contrasenna_asterisco)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btn_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lbl_ingreso)
                .addGap(34, 34, 34)
                .addComponent(lbl_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_usuario_asterisco))
                .addGap(18, 18, 18)
                .addComponent(lbl_contrasenna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtp_contrasenna, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_contrasenna_asterisco))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtp_contrasennaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtp_contrasennaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtp_contrasennaActionPerformed

    private void btn_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entrarActionPerformed
        lbl_usuario_asterisco.setVisible(false);
        lbl_contrasenna_asterisco.setVisible(false);
        
        if (txtf_usuario.getText().equals("")) {
            lbl_usuario_asterisco.setVisible(true);
        } 
        if (String.valueOf(txtp_contrasenna.getPassword()).equals("")) {
            lbl_contrasenna_asterisco.setVisible(true);
        } else {
            Connection con = MiConexion.getConnection();
            PreparedStatement ps;
            
            try {
                ps = con.prepareStatement("SELECT * FROM usuario WHERE usuario = ? AND contrasenna = ?");
                ps.setString(1, txtf_usuario.getText());
                ps.setString(2, String.valueOf(txtp_contrasenna.getPassword()));
                
                ResultSet rs = ps.executeQuery();
                
                if (rs.next()) {
                    FormularioPrincipal fp = new FormularioPrincipal();
                    fp.setVisible(true);
                    fp.pack();
                    fp.setLocationRelativeTo(null);
                    //fp.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    FormularioPrincipal.lbl_bienvenido.setText("Hola, "+txtf_usuario.getText());
                    FormularioPrincipal.lbl_cant_est.setText("Cantidad de estudiantes: "+Integer.toString(MiFuncion.contarData("estudiante")));
                    FormularioPrincipal.lbl_cant_cur.setText("Cantidad de cursos: "+Integer.toString(MiFuncion.contarData("curso")));
                    
                    this.dispose();
                            
                } else {
                    System.out.println("No");
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_entrarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_contrasenna;
    private javax.swing.JLabel lbl_contrasenna_asterisco;
    private javax.swing.JLabel lbl_ingreso;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JLabel lbl_usuario_asterisco;
    private javax.swing.JTextField txtf_usuario;
    private javax.swing.JPasswordField txtp_contrasenna;
    // End of variables declaration//GEN-END:variables
}
